version: '3.7'

services:
  mongo:
    image: mongo:4.0-xenial
    command: --bind_ip_all
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017

  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./logs/:/opt/javaSrv/logs
    depends_on:
      - mongo